### ISSUE TITLE
Can you add the ability to use Named Credentials instead of setting headers (including authentication) in the code

### ISSUE THREAD

**Issue by stephenpstanley** [IlyaMatsuev/Apex-GraphQL-Client#37]
### What is missing from the application? Please describe.
I'd like the ability to used Named and External credentials instead of having to risk exposing Authentication tokens either in code or in some other setting.  Named and external credentials also provide the ability to change both endpoints used and authentication and callout headers without having to edit APEX code. It can be done using configuration

### Describe the solution you'd like
Currently to send a request, you need to do something like this:

GraphQLRequest request = new GraphQLRequest(query)
    .withHeader('Authorization', 'Bearer token');
// Provide GraphQL endpoint to the client constructor
GraphQLHttpClient client = new GraphQLHttpClient('https://your-gql-endpoint-url.com');

Using Named and External credentials, you'd create an External Credential (let's call it "GraphqlExternal") with a Named Principal called "Authorization" with a parameter called "Authorization" and value of the API Key
You'd then create a Named Credential (let's call it "GraphqlNamed")  that uses that External Credential and allows formulas in the header.  You'd add a Custom Header entry called "Authorization" and a formula value of {!$Credential.GraphqlExternal.Authorization}   You can also set other Header name-value pairs required such as 
Content-Type = application/json

In your code, you'd then have a single line

GraphQLHttpClient client = new GraphQLHttpClient('callout:GraphqlNamed');

... which mimics how you'd used a Named Credential in a req.setEndPoint() command in System APEX

### Describe alternatives you've considered

I've considered hardcoding credentials / API keys in code but this risks them leaking.  It also means that you can't run the same code across sandboxes and production environments unless you put keys in a custom setting or custom metadata (which also risks leaks)

**Comment by IlyaMatsuev** [comment]
Hi @stephenpstanley, thanks for your issue! Sounds like a nice feature indeed, I will see what I can do. Perhaps, I will be able to start during the next week

**Comment by stephenpstanley** [comment]
Hi Ilya

Thanks for the quick response. I'm looking at using your managed package for a corporate customer of mine - is it listed on the AppExchange and has it gone through the salesforce security review?

Stephen
________________________________

**Comment by IlyaMatsuev** [comment]
@stephenpstanley it's not a managed package, it's an unmanaged package that can be installed using the instructions from the readme file. It's not published to AppExchange. Therefore no, it didn't go through Salesforce security review

**Comment by IlyaMatsuev** [comment]
Hi @stephenpstanley,

I made a few tests and seems that you can already use named credentials like this:

```java
GraphQLField countriesNode = new GraphQLField('countries')
    .withFields(new List<String> { 'name', 'capital' })
    .withField(new GraphQLField('languages').withField('name'))
    .withArgument('filter', new Map<String, Object> {
        'currency' => new Map<String, String> { 'eq' => 'EUR' },
        'continent' => new Map<String, String> { 'eq' => 'EU' }
    });

GraphQLQuery query = new GraphQLQuery(countriesNode);

System.debug('query: ' + query.build(true));

GraphQLRequest request = new GraphQLRequest(query);

// Specify named credentials here
GraphQLHttpClient client = new GraphQLHttpClient('callout:TestConnection');
GraphQLResponse response = client.send(request);

System.debug('response data: ' + JSON.serializePretty(response.getData()));
```

When sending GQL request, I'm still using the standard `HttpRequest` Apex class. So when you provide an endpoint like `callout:something`, Salesforce tries to find the named credentials with that name and alters the instance of `HttpRequest` right before it gets sent, setting the proper endpoint and headers.
Therefore, no changes are required here, you can go ahead and use named credentials like you proposed :)

Although, I'm going to put a not in the documentation about using named credentials.

**Comment by stephenpstanley** [comment]
That’s great news. I must admit I read the docs but didn’t every try it

I’ll alter my code and see how it goes
Stephen Stanley

On 24 Dec 2024, at 04:50, Ilya Matsuev ***@***.***> wrote:

﻿

Hi @stephenpstanley<https://github.com/stephenpstanley>,

I made a few tests and seems that you can already use named credentials like this:

GraphQLField countriesNode = new GraphQLField('countries')
    .withFields(new List<String> { 'name', 'capital' })
    .withField(new GraphQLField('languages').withField('name'))
    .withArgument('filter', new Map<String, Object> {
        'currency' => new Map<String, String> { 'eq' => 'EUR' },
        'continent' => new Map<String, String> { 'eq' => 'EU' }
    });

GraphQLQuery query = new GraphQLQuery(countriesNode);

System.debug('query: ' + query.build(true));

GraphQLRequest request = new GraphQLRequest(query);

// Specify named credentials here
GraphQLHttpClient client = new GraphQLHttpClient('callout:TestConnection');
GraphQLResponse response = client.send(request);

System.debug('response data: ' + JSON.serializePretty(response.getData()));

When sending GQL request, I'm still using the standard HttpRequest Apex class. So when you provide an endpoint like callout:something, Salesforce tries to find the named credentials with that name and alters the instance of HttpRequest right before it gets sent, setting the proper endpoint and headers.
Therefore, no changes are required here, you can go ahead and use named credentials like you proposed :)

Although, I'm going to put a not in the documentation about using named credentials.

**Comment by stephenpstanley** [comment]
Perfect. Thank you
________________________________
